name: Deploy on Github Pages

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js environment
              uses: actions/setup-node@v3.1.1
            - name: "Install dependencies 💿"
              run: npm ci
#            - name: "Apply my Google Analytics key 📈"
#              run: mv .env.example .env && sed -i "s/xxx/${{ secrets.GOOGLE_ANALYTICS }}/" .env
            - name: "Build project 🔨"
              run: npm run generate
            - name: "Create CNAME 📄"
              run: printf "${{ secrets.CNAME }}" > dist/CNAME
            - name: "Deploy to GitHub Pages 🌐"
              uses: crazy-max/ghaction-github-pages@v2
              with:
                  target_branch: gh-pages
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
