name: Deploy to Hosting

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
      - run: npm ci
      - run: npm run build
      - uses: Atyn/simple-sftp-action@main
        with:
          url: sftp://${{ secrets.SFTP_USERNAME }}:${{ secrets.SFTP_PASSWORD }}@${{ secrets.SFTP_ADDRESS }}/www
          local-directory: dist
