name: Deploy to Hosting

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - uses: wangyucode/sftp-upload-action@main
        with:
          host: "${{ secrets.SFTP_ADDRESS }}"
          username: "${{ secrets.SFTP_USERNAME }}"
          password: "${{ secrets.SFTP_PASSWORD }}"
          localDir: "dist"
          remoteDir: "/home/${{ secrets.SFTP_USERNAME }}/www"
